<!doctype html>
<html lang="en">
<?php
$title = 'Добавить новое сообщение';
$this->headTitle($title);
?>
<body>
<h1><?php
    echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('guest', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('email')) . "<br>";
echo $this->formRow($form->get('text')) . "<br>";
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<?php
$title = 'Гостевая книга';
$this->headTitle($title);
?>
<style>
    table {
        width: 50%;
        background: palegreen;
        border-width: 5px;
    }
</style>
<table class="guestTable">
    <tr>
        <th>Почта</th>
        <th>Текст сообщения</th>
        <th></th>
    </tr>
    <?php
    foreach ($data as $empdata) : ?>
        <tr>
            <td><?php
                echo $this->escapeHtml($empdata->email); ?></td>
            <td><?php
                echo $this->escapeHtml($empdata->text); ?></td>

        </tr>
    <?php
    endforeach; ?>
</table>
</body>
</html>